In [6]:
import matplotlib.pyplot as plt

def unpickle(file): 
    import pickle 
    with open(file, 'rb') as fo: 
        dict = pickle.load(fo,encoding='bytes') 
    return dict

print("="*50)
print("字典里的内容:")
data1 = unpickle("data_batch_1")
print(data1.keys())

# batch_label 里面存的内容
print("="*50)
print("batch_label 里面存的内容:")
batch_label = data1[b'batch_label'].decode('utf-8')
print(f"batch_label: {batch_label}")

# 每个键对应值的内容
for key, value in data1.items():
    key_str = key.decode('utf-8')
    type_info = f"type: {type(value)}"
    
    if isinstance(value, list):
        print(f"key: {key_str}, {type_info}")
        print(f"  list_en: {len(value)}")
        print(f"  前5个: {value[:5]}")
    elif isinstance(value, dict):
        print(f"key: {key_str}, {type_info}")
        print(f"  dict_keys: {str(value.keys())}")
    elif hasattr(value, 'shape'):
        print(f"key: {key_str}, {type_info}")
        print(f"  shape: {value.shape}")
        print(f"  前5个: \n{value[:5]}")
    else:
        print(f"key: {key_str}, {type_info}")

    print("="*50)


字典里的内容:
dict_keys([b'batch_label', b'labels', b'data', b'filenames'])
batch_label 里面存的内容:
batch_label: training batch 1 of 5
key: batch_label, type: <class 'bytes'>
key: labels, type: <class 'list'>
  list_en: 10000
  前5个: [6, 9, 9, 4, 1]
key: data, type: <class 'numpy.ndarray'>
  shape: (10000, 3072)
  前5个: 
[[ 59  43  50 ... 140  84  72]
 [154 126 105 ... 139 142 144]
 [255 253 253 ...  83  83  84]
 [ 28  37  38 ...  28  37  46]
 [170 168 177 ...  82  78  80]]
key: filenames, type: <class 'list'>
  list_en: 10000
  前5个: [b'leptodactylus_pentadactylus_s_000004.png', b'camion_s_000148.png', b'tipper_truck_s_001250.png', b'american_elk_s_001521.png', b'station_wagon_s_000293.png']
